{
  "Albernische Wälder (gem. Klima)": 1,
  "Almadanische Wälder (yaquirisches Klima)": 1,
  "Andere Mittelländische Gebirge": 3,
  "Ehernes Schwert": 3,
  "Havener Marschen": 3,
  "Immergrüne Wälder (Südosten)": 1,
  "Koschberge": 3,
  "Liebfeldische Wälder (yaquirisches Klima)": 1,
  "Maraskan": 1,
  "Mengbillanische Wälder (yaquirisches Klima)": 1,
  "Mitelländische Wälder (tobrisches Klima)": 2,
  "Mittelaventurische Kalkgebirge": 3,
  "Mittelländische Grasländer (Heide und Steppe)": 1,
  "Mittelländische Wälder (gem. Klima)": 1,
  "Mittelländische Wälder (yaquirisches Klima)": 1,
  "Nördliche Grasländer und Steppen": 2,
  "Nördliche Kalkgebirge": 3,
  "Nördliche Sümpfe (Marschen und Moore)": 3,
  "Nördliche Tundra": 3,
  "Nördliche Wälder (Bornland)": 0,
  "Nördliche Wälder (Taiga)": 0,
  "Nördliche Wälder (Westküste)": 1,
  "Nördliches Hochland": 2,
  "Regenwald": 0,
  "Rote Sichel": 3,
  "Salamandersteine": 3,
  "Schwarze und Gelbe Sichel": 3,
  "Südliche Regengebirge": 2,
  "Südliche Sümpfe": 3,
  "Südländische Gebirge": 3,
  "Südländische Grasländer und Steppen": 2,
  "Walberge": 3,
  "Windhagberge und Finsterkamm": 3,
  "Wüste": 4,
  "Wüstenrandgebiete": 3
}
